# Generated by Django 2.2.1 on 2019-05-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_movmensalista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movrotativo',
            name='valor_hora',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
