# Generated by Django 2.2.1 on 2019-05-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190526_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movrotativo',
            name='valor_hora',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
